# -*- coding: utf-8 -*-
"""FDS Practical (23.09.21)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nJZiYRwzooHtU-XHu7khp9sUAm2r_Fql
"""

post= input("What is the post")
month = {"January" : 31, "February" : 28, "March" : 31, "April" :30, "May" : 31, "June": 30, "July": 31, "August": 31, "September" :30, "October": 31, "November" : 30, "December" :31}
months = input("Enter the month of the salary:")
days = int(input("How many days of working"))
salary = 0
if post == "Manager":
  if days<32:
    salary += days * 2000
    ask_overt = int(input("How many days of overtime"))
    if ask_overt >= 0:
      salary += ask_overt*(2000/2)
      print (salary)
    else:
        print("Wrong input")

if post == "Team Leader":
  if days<32:
    salary += days * 1800
    ask_overt = int(input("How many days of overtime"))
    if ask_overt >= 0:
      salary += ask_overt*(1800/2)
      print (salary)
    else:
        print("Wrong input")

if post == "Member":
  if days<32:
    salary += days * 1500
    ask_overt = int(input("How many days of overtime"))
    if ask_overt >= 0:
      salary += ask_overt*(1500/2)
      print (salary)
    else:
        print("Wrong input")