# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17vBi9aI95v4IxGbsMkOz3hVTxaZw7ZPE
"""



def set_a():
  a = []
  an = int(input("Enter the no of students you want to add in set A :"))

  for i in range (an):
    num1 = int(input("Enter the number : "))
    a.append(num1)
    print(a)

def set_b():
      b = []
      bn = int(input("Enter the no of students you want to add in set B :"))

      for i in range(bn):
        num2 = int(input("Enter the number : "))
        b.append(num2)
        print(b)

def set_c():
          c = []
          cn = int(input("Enter the no of students you want to add in set c : "))
          c.append(num1)
          print (c)

set_a()
set_b()
set_c()

import array as arr
d=int (input("Enter the number of values"))
ip=arr.array("i", [])
for i in range (0,d):
  val=int (input("Enter Value"))
  ip.append(val)
sum=0
for i in range(len(ip)) :
  sum = sum + ip[i]
average=0
avg= sum/len(ip)
print(ip)
print (sum)
print(avg)