# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17vBi9aI95v4IxGbsMkOz3hVTxaZw7ZPE
"""



import array as arr
d=int (input("Enter the number of values"))
ip=arr.array("i", [])
for i in range (0,d):
  val=int (input("Enter Value"))
  ip.append(val)
sum=0
for i in range(len(ip)) :
  sum = sum + ip[i]
average=0
avg= sum/len(ip)
print(ip)
print (sum)
print(avg)